---
header-includes:
- \usepackage{longtable}
- \usepackage[utf8]{inputenc}
- \usepackage[spanish]{babel}\decimalpoint
- \usepackage{graphicx}
output:
  pdf_document: default
fontsize: 12pt
papersize: letter
geometry: margin = 1in
language: "es"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, comment = NA, fig.pos = "H")
library(knitr)
```

**Estadística II - Taller 08$\hspace{1.6cm}$Semestre: 2021-02**

**Profesores: Carlos M. Lopera-Gómez y Raúl Alberto Pérez**

**Monitor: Simon Pedro Galeano**

$\rule{6.5in}{1pt}$

1. Responda las siguientes preguntas.
a) Suponga que se ajusta un modelo de regresión con una variable categórica, sin interacción,
¿dicho modelo genera rectas secantes?
b) En un modelo de regresión lineal simple ajustado solo con factores, las rectas
generadas son horizontales.
c) El parámetro $\beta_j$ es la media de $Y$ en la categoría $j$ en el modelo de 
regresión $Y = \beta_0 + \sum_{k = 1}^{c-1}\beta_k I_{k}$, en caso de que no, ¿cuál es
la media?
d) La interacción entre variables numéricas y categóricas hace variar la tasa de 
cambio de la respuesta en cada categoría de la variable categórica.

2. Use la base de datos mtcars para ajustar el siguiente modelo $$mpg = \beta_0 + \beta_1 \text{wt} + \beta_2 \text{cyl} + \beta_3 \text{wt}\times\text{cyl}$$ 
intreprete los coeficientes de la regresión.

3. Usando la base de datos rock lleve a cabo los métodos de selección forward, backward y
stepwise. Concluya cual de los tres modelos obtenidos es el mejor. Para dicha tarea
se puede apoyar en la tabla de todas las regresiones posibles.